export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';

export const USER_LIST_START = 'USER_LIST_START';
export const USER_LIST_SUCCESS = 'USER_LIST_SUCCESS';
export const USER_LIST_FAIL = 'USER_LIST_FAIL';

export const CREATE_PROJECT_START = 'CREATE_PROJECT_START';
export const CREATE_PROJECT_SUCCESS = 'CREATE_PROJECT_SUCCESS';
export const CREATE_PROJECT_FAIL = 'CREATE_PROJECT_FAIL';

export const PROJECT_LIST_START = 'PROJECT_LIST_START';
export const PROJECT_LIST_SUCCESS = 'PROJECT_LIST_SUCCESS';
export const PROJECT_LIST_FAIL = 'PROJECT_LIST_FAIL';

export const GET_PROJECT_DETAIL_START = 'GET_PROJECT_DETAIL_START';
export const GET_PROJECT_DETAIL_SUCCESS = 'GET_PROJECT_DETAIL_SUCCESS';
export const GET_PROJECT_DETAIL_FAIL = 'GET_PROJECT_DETAIL_FAIL';

export const CREATE_SECTOR_START = 'CREATE_SECTOR_START';
export const CREATE_SECTOR_SUCCESS = 'CREATE_SECTOR_SUCCESS';
export const CREATE_SECTOR_FAIL = 'CREATE_SECTOR_FAIL';

export const SECTOR_LIST_START = 'SECTOR_LIST_START';
export const SECTOR_LIST_SUCCESS = 'SECTOR_LIST_SUCCESS';
export const SECTOR_LIST_FAIL = 'SECTOR_LIST_FAIL';

export const GET_SECTOR_DETAIL_START = 'GET_SECTOR_DETAIL_START';
export const GET_SECTOR_DETAIL_SUCCESS = 'GET_SECTOR_DETAIL_SUCCESS';
export const GET_SECTOR_DETAIL_FAIL = 'GET_SECTOR_DETAIL_FAIL';

export const CREATE_MEETING_START = 'CREATE_MEETING_START';
export const CREATE_MEETING_SUCCESS = 'CREATE_MEETING_SUCCESS';
export const CREATE_MEETING_FAIL = 'CREATE_MEETING_FAIL';

export const MEETING_LIST_START = 'MEETING_LIST_START';
export const MEETING_LIST_SUCCESS = 'MEETING_LIST_SUCCESS';
export const MEETING_LIST_FAIL = 'MEETING_LIST_FAIL';

export const MEETING_ALL_LIST_START = 'MEETING_ALL_LIST_START';
export const MEETING_ALL_LIST_SUCCESS = 'MEETING_ALL_LIST_SUCCESS'; 
export const MEETING_ALL_LIST_FAIL = 'MEETING_ALL_LIST_FAIL';

export const GET_MEETING_DETAIL_START = 'GET_MEETING_DETAIL_START';
export const GET_MEETING_DETAIL_SUCCESS = 'GET_MEETING_DETAIL_SUCCESS';
export const GET_MEETING_DETAIL_FAIL = 'GET_MEETING_DETAIL_FAIL';

export const CREATE_QUESTTIONAIRE_QUIZ_START = 'CREATE_QUESTTIONAIRE_QUIZ_START'; 
export const CREATE_QUESTTIONAIRE_QUIZ_SUCCESS = 'CREATE_QUESTTIONAIRE_QUIZ_SUCCESS';
export const CREATE_QUESTTIONAIRE_QUIZ_FAIL = 'CREATE_QUESTTIONAIRE_QUIZ_FAIL';

export const GET_QUESTTIONAIRE_MEETING_LIST_START = 'GET_QUESTTIONAIRE_MEETING_LIST_START';
export const GET_QUESTTIONAIRE_MEETING_LIST_SUCCESS = 'GET_QUESTTIONAIRE_MEETING_LIST_SUCCESS';
export const GET_QUESTTIONAIRE_MEETING_LIST_FAIL = 'GET_QUESTTIONAIRE_MEETING_LIST_FAIL';

export const GET_QUESTTIONAIRE_DETAIL_START = 'GET_QUESTTIONAIRE_DETAIL_START';
export const GET_QUESTTIONAIRE_DETAIL_SUCCESS = 'GET_QUESTTIONAIRE_DETAIL_SUCCESS';
export const GET_QUESTTIONAIRE_DETAIL_FAIL = 'GET_QUESTTIONAIRE_DETAIL_FAIL';

export const GET_QUESTION_QUESTTIONAIRE_DETAIL_START = 'GET_QUESTION_QUESTTIONAIRE_DETAIL_START';
export const GET_QUESTION_QUESTTIONAIRE_DETAIL_SUCCESS = 'GET_QUESTION_QUESTTIONAIRE_DETAIL_SUCCESS';
export const GET_QUESTION_QUESTTIONAIRE_DETAIL_FAIL = 'GET_QUESTION_QUESTTIONAIRE_DETAIL_FAIL';